# .github/workflows/ci.yaml
# Keep existing CI workflow - assumes it handles venv creation and pytest execution.
# Example structure (adapt if needed):
name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"] # Match supported versions

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest # Ensure pytest is installed

    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest app/tests/ # Run tests from the new location
