# .github/workflows/ci.yml
name: Python Application CI

on:
  push:
    branches: [ "main" ] # Or your default branch
  pull_request:
    branches: [ "main" ] # Or your default branch

permissions:
  contents: read # Needed to check out the code

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # Checks out your repository code

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Optional: Add linting step (e.g., using flake8 or ruff)
    # - name: Lint with flake8
    #   run: |
    #     pip install flake8
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run Tests with pytest
      run: |
        # Ensure the tests directory exists and run pytest
        # The PYTHONPATH might need adjustment if tests can't find modules
        # export PYTHONPATH="${PYTHONPATH}:${GITHUB_WORKSPACE}" # Add project root to PYTHONPATH
        pytest tests/ # Run tests from the tests directory